# Generated by Django 6.0.5 on 2026-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_name', models.CharField(max_length=255, verbose_name='Mess Name')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Contains all details of the mess, including timings, menus, leave policies, etc.', verbose_name='Description')),
                ('location', models.JSONField(blank=True, default=dict, help_text="JSON containing location details compatible with OpenStreetMap (e.g. {'lat': 0.0, 'lng': 0.0, 'address': ''})", verbose_name='Location Coordinates & Address')),
                ('food_per_day', models.PositiveIntegerField(default=3, help_text='Normally every mess provides 3 meals per day', verbose_name='Meals Per Day')),
                ('subscription_rate', models.DecimalField(decimal_places=2, help_text='Monthly subscription rate', max_digits=10, verbose_name='Monthly Subscription Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mess',
                'verbose_name_plural': 'Messes',
                'ordering': ['-created_at'],
            },
        ),
    ]
